back

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -169,22 +169,22 @@ jobs:
           name: Install tar utility
           command: |
             yum install -y tar gzip
-      # - run:
-      #     name: Ensure back-end infrastructure exists
-      #     command: |
-      #       aws cloudformation deploy \
-      #         --template-file .circleci/files/backend.yml \
-      #         --tags project=udapeople \
-      #         --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID}" \
-      #         --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"
-      # - run:
-      #     name: Ensure front-end infrastructure exist
-      #     command: |
-      #       aws cloudformation deploy \
-      #         --template-file .circleci/files/frontend.yml \
-      #         --tags project=udapeople \
-      #         --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID}" \
-      #         --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"
       - run:
           name: Add back-end ip to ansible inventory
           command: |
@@ -316,31 +316,43 @@ jobs:
           fingerprints: ["90:87:c7:ea:5c:87:5b:c8:5f:fa:09:23:fb:66:c7:db"]
       - attach_workspace:
           at: ~/workspace
-      - restore_cache:
-          keys: [backend-build]
-      - run:
-          name: Install dependencies
-          command: |
-            cd backend 
-            npm install
       - run:
           name: Package backend
           command: |
             cd backend
+            npm i
             npm run build
-            tar -czf artifact.tar.gz dist/* package*
+            echo "NODE_ENV=production" >.env
+            echo "VERSION=1" >>.env
+            echo "TYPEORM_CONNECTION=postgres" >>.env
+            echo "TYPEORM_MIGRATIONS_DIR=./src/migrations" >>.env
+            echo "TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts" >>.env
+            echo "TYPEORM_MIGRATIONS=./src/migrations/*.ts" >>.env
+
+            echo "# Things you can change if you wish..." >>.env
+            echo "TYPEORM_HOST=postgres.cazdb8tjarlp.us-east-1.rds.amazonaws.com" >>.env
+            echo "TYPEORM_PORT=5432" >>.env
+            echo "TYPEORM_USERNAME=postgres" >>.env
+            echo "TYPEORM_PASSWORD=mypassword" >>.env
+            echo "TYPEORM_DATABASE=postgres" >>.env       
             cd ..
-            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+            # Zip the directory
+            tar -C backend -czvf artifact.tar.gz .
+
+            # tar -czvf artifact.tar.gz backend
+            cp artifact.tar.gz .circleci/ansible/roles/deploy/files
             pwd
             cd /home/circleci/project/.circleci/ansible/roles/deploy/files && ls
       - run:
           name: Deploy backend
           command: |
             cd .circleci/ansible
-            cat ~/workspace/inventory.txt
-            ansible-playbook -i ~/workspace/inventory.txt deploy-backend.yml
-      # - destroy-environment
-      # - revert-migrations
+            echo [web] > inventory.txt && aws ec2 describe-instances --filters "Name=tag:project,Values=udapeople" \
+              --query "Reservations[*].Instances[*].PublicIpAddress" --output text >> inventory.txt
+            cat inventory.txt
+            ansible-playbook -i inventory.txt deploy-backend.yml
+      - destroy-environment
+      - revert-migrations
 
   smoke-test:
     docker:
@@ -348,7 +360,7 @@ jobs:
     steps:
       - checkout
       - install_awscli
-      - install_nodejs
+      # - install_nodejs
       - run:
           name: Backend smoke test
           command: |
@@ -372,7 +384,7 @@ jobs:
             FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com
             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
             then
-              exit 0
+              exit 1
             else
               exit 1
             fi 
@@ -382,32 +394,36 @@ jobs:
 workflows:
   default:
     jobs:
-      # - build-frontend
-      # - build-backend
-      # - test-frontend:
-      #     requires: [build-frontend]
-      # - test-backend:
-      #     requires: [build-backend]
-      # - scan-backend:
-      #     requires: [build-backend]
-      # - scan-frontend:
-      #     requires: [build-frontend]
-      # - deploy-infrastructure:
-      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-      #     filters:
-      #       branches:
-      #         only: [master]
-      # - configure-infrastructure:
-      #     requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
-      # - deploy-frontend:
-      #     requires: [run-migrations]
-      
-      - deploy-infrastructure
-      - deploy-backend:
+      - build-frontend
+      - build-backend
+      - test-frontend:
+          requires: [build-frontend]
+      - test-backend:
+          requires: [build-backend]
+      - scan-backend:
+          requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          filters:
+            branches:
+              only: [master]
+      - configure-infrastructure:
           requires: [deploy-infrastructure]
-          # requires: [run-migrations]
-      - smoke-test: 
-          # requires: [deploy-backend, deploy-frontend]
-          requires: [deploy-backend]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations]
+      - deploy-backend :
+          requires: [run-migrations]
+      - smoke-test :
+          requires: [deploy-backend, deploy-frontend]
+      # - deploy-backend
+      # - smoke-test :
+      #     requires: [deploy-backend]
+
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
